name: pizza_repository
description: The Repo that handles pizzas
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependecies:
  flutter:
    sdk: flutter
  
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2

dart_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
dependencies:
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
